# Generated by Django 3.2.14 on 2022-07-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photos/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.products')),
            ],
        ),
    ]
