# Generated by Django 3.2.14 on 2022-07-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photos',
            new_name='photo',
        ),
    ]
