# Generated by Django 3.2.14 on 2022-07-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
